@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package io.github.mrp_v2.betterservergui;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;